### ISSUE TITLE
Clear output before every test

### ISSUE THREAD

**Issue by jiriko** [elonmallin/vscode-phpunit#13]
How to clear output first in the terminal before every test?

**Comment by elonmallin** [comment]
Hi, there is no way to do it automatically right now. I would need to add a config flag to enable that if it's a requested feature.

It is however possible to clear the output channel manually just like the other terminals in VSCode.

**Comment by jiriko** [comment]
Ok. I wish that was possible. Thanks

**Comment by elonmallin** [comment]
If you want to contribute that you're free to do so. It should be a relatively easy thing to add. And might be a good size ticket if you're interested in developing extensions for VSCode :)

Otherwise I can add it sometime later.

**Comment by elonmallin** [comment]
I want to make it configurable too so that it doesn't force clear the output after every run. I believe people have different preferences here. So I'll add an option like `clearOutputOnRun: boolean`.

**Comment by elonmallin** [comment]
This should now work in the latest release [v3.0.0](https://github.com/elonmallin/vscode-phpunit/releases/tag/v3.0.0) also published to the [marketplace](https://marketplace.visualstudio.com/items?itemName=emallin.phpunit).
