### ISSUE TITLE
bind keyboard shortcut for running test for entire folder

### ISSUE THREAD

**Issue by jiriko** [elonmallin/vscode-phpunit#14]
How to bind keyboard shortcut for entire folder?
something like 
```
  {
        "key": "ctrl+t",
        "command": "phpunit.Test",
        "when": "editorTextFocus"
    },
```
but for entire folder?

**Comment by elonmallin** [comment]
Hi, the command for that is `phpunit.TestDirectory`.

You can see the contributing commands in https://github.com/elonmallin/vscode-phpunit/blob/master/package.json

**Comment by jiriko** [comment]
thanks man. great job!!
