### ISSUE TITLE
Using phpunit.phar

### ISSUE THREAD

**Issue by naxvog** [elonmallin/vscode-phpunit#18]
This cost me a considerable amount of time to figure out.

I was trying to use phpunit.phar and added the path to the configuration. Spawning the process failed so I decided to dig deeper. Long story short:

    "phpunit.execPath": "php", // path to php or php command
    "phpunit.args": [
        "C:\\php\\phpunit-6.4.4.phar" // path to phpunit.phar
    ],

did the trick! (using Win10 but should apply to any OS)

Would be nice to add some kind of annotation to the setup instructions.

cheers

**Comment by elonmallin** [comment]
Sorry for that, but it's true. I'm also on windows but I use composer. I've created a .bat file for the `execPath`.

With content: `php ../phpunit/phpunit/phpunit %*`. Runs php with phpunit as input file and tags on any arguments. You could do the same if you like but your solution also works.

Either way, I should make it more clear in the readme.

**Comment by elonmallin** [comment]
I released [v3.0.0](https://github.com/elonmallin/vscode-phpunit/releases/tag/v3.0.0) (also published to the [marketplace](https://marketplace.visualstudio.com/items?itemName=emallin.phpunit)) and it will find a `composer.phar` file automatically if it's in the project folder and use that without any configuration. `php` is also not needed if it's in the global environment variables.
