### ISSUE TITLE
Add the ability to run tests from the source code files

### ISSUE THREAD

**Issue by cpliakas** [elonmallin/vscode-phpunit#19]
First off, this is an excellent extension. I love how easy it is to run individual tests via `cmd + shift + P`.

There is a feature in the Golang extension which I feel would be great to incorporate into this extension to make running tests even easier. Specifically, there is a code lens that enables you to run tests right from the source code files as show in the image below:

<img width="578" alt="screen shot 2017-11-12 at 8 31 13 am" src="https://user-images.githubusercontent.com/482722/32699560-9cf6f68a-c785-11e7-84aa-c967364657b2.png">

I'm not positive, but it seems that the code at https://github.com/Microsoft/vscode-go/blob/master/src/goRunTestCodelens.ts is where the magic happens in the Golang extension. Anyways, I thought it would be worth posting here for feedback as to whether this would be useful, and if so, possible to implement in this extension.

**Comment by elonmallin** [comment]
Thanks, yes that should be possible to add.

Would need some restrictions to which files and functions they would appear on though:
- A file must end in *Test.php
- Function must start with test* or have @test in the docblock [docs](https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html)

Then we could add these (code lenses?) to test the whole class or single tests.

I'd also add a flag: disableCodeLense: default false.

**Comment by elonmallin** [comment]
Added this feature now ages later and released a new version [4.8.0](https://github.com/elonmallin/vscode-phpunit/releases/tag/4.8.0)
