### ISSUE TITLE
Not working at all,

### ISSUE THREAD

**Issue by ryanbowden** [elonmallin/vscode-phpunit#2]
Hello,

I am running ubuntu 14.04,

And have followed the documentation to install it and used the two example files php unit has, 

But it not running any tests.

All i get is this in the output
`/usr/local/bin/phpunit --configuration ./phpunit.xml.dist ./tests/MoneyTest.php
This version of PHPUnit requires PHP 5.6; using the latest version of PHP is highly recommended.`

Any help? 

Please let me know if you need any information.

**Comment by ryanbowden** [comment]
Stilly me should read the error better.

**Comment by elonmallin** [comment]
Yea, hope updating your PHP version helped :)
