### ISSUE TITLE
Cancel Tests

### ISSUE THREAD

**Issue by Blfrg** [elonmallin/vscode-phpunit#23]
I don't see a way to cancel the current test(s) in progress.

For example: Some tests require that I connect to a VPN but I may forget in advance.
Then I must wait for the tests to time out which could take a while.

If I connect to the VPN and start a new set of tests, the output of the previous tests may interject into the output and cause confusion about what has been successful or failed.

A button on the 'Output' pane, or a hotkey to stop currently running tests would be helpful.

Thank you for the truly essential plugin!

**Comment by yoongshang** [comment]
I made a pr for this function.
#29

**Comment by Blfrg** [comment]
@yoongshang Thank you for this! I hope it gets accepted

**Comment by elonmallin** [comment]
Thanks for the PR, great help! I published a release today [v3.1.0](https://github.com/elonmallin/vscode-phpunit/releases/tag/v3.1.0).
