### ISSUE TITLE
Able to add keybindings 

### ISSUE THREAD

**Issue by ryanbowden** [elonmallin/vscode-phpunit#3]
In VS code i want to be able to add a key binding for running the tests without having to type it in every time

`// Place your key bindings in this file to overwrite the defaults
[
{
    "key": "ctrl+f8",
    "command": "phpunit",
    "when": "editorTextFocus"
}]`

I tried that but it does not work. How would i do it?

**Comment by elonmallin** [comment]
The command name needs to be either phpunit.Test or phpunit.TestDirectory. You can check the commands section in the [package.json](https://github.com/elonmallin/vscode-phpunit/blob/master/package.json).

This should work, seems someone has tested it if you look at the review on the [vscode marketplace](https://marketplace.visualstudio.com/items?itemName=emallin.phpunit).

Cheers,
Elon
