### ISSUE TITLE
Failed to create terminal for task when running automatic tasks

### ISSUE THREAD

**Issue by nerdo** [elonmallin/vscode-phpunit#31]
- VSCode Version: 1.32.3
- OS Version: macOS Mojave 10.14.3

Steps to Reproduce:

Automatic tasks seem to interfere with extensions that need to run tasks.

I use a PHPUnit extension (https://github.com/elonmallin/vscode-phpunit) and I find that whenever I launch a workspace that runs automatic tasks, the phpunit commands fail with an error message saying `Failed to create terminal for task phpunit: run`.

Turning off the automatic tasks seems to fix the issue.

FYI I also reported this in the vscode repo (https://github.com/Microsoft/vscode/issues/70904) because I'm not sure if the issue is with the vscode host or the plugin.

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by elonmallin** [comment]
Looks like this is a VSCode issue. This one seems related https://github.com/Microsoft/vscode/issues/70557.
Should be fixed in the insiders version. Maybe you could try there? I'll close this one.
