### ISSUE TITLE
Problem configuring path to phpunit.xml

### ISSUE THREAD

**Issue by xastor** [elonmallin/vscode-phpunit#33]
I have a project where i have 2 php libraries with their own sets of tests.  I have different phpunit.xml files for them, located in the parent folder of each test suite.  

Is there a variable I can use, to point to the phpunit.xml file using a path relative to the test suite?  Something like this :
```
    "phpunit.args": [
        "--configuration", "${testSuite}/../phpunit.xml"
    ]
```

**Comment by xastor** [comment]
I found out that when not providing the --configuration argument to phpunit, the phpunit.xml file in the current working directory is used, if present.

The plugin could search for the phpunit.xml closest to the test suite (look in parent directories until at project root) and then set the working directory to that folder before running the test suite.

Just trying to think about any possible solutions to my problem.  What are your thoughts on this?  I would be down for helping to implement this.

**Comment by elonmallin** [comment]
Sounds like a good idea =)

I thinks there should be just the 2 cases then:
1. `--configuration` is not set so we look in the current working dir first and then traverse up like you explained or if the other way around is better.
2. `--configuration` is set so we just use that one.

I'd happily take any help I could get. It could probably be added in the `run` function in `phpunittest.ts`.

**Comment by elonmallin** [comment]
I added a `phpunit.TestSuite` command at this [commit](https://github.com/elonmallin/vscode-phpunit/commit/516ac9d15fd611aa1a5305da4e55ecf58e3f970b). Which finds all `**phpunit.xml**` files in the project and lets you pick the one you wish to run. Furthermore it then shows the `<testsuites>` in a quick pick windows so you can run individual or all tests in the suite.

The default command `phpunit.Test` will now also trigger the same behavior if the current file is a `phpunit.xml` file or `phpunit.xml.dist`.

Closing this as I think this solution will be ok =)

**Comment by RaiserWeb** [comment]
I'm trying to run tests on a monorepo - there are multiple package folders all with different phpunit.xml files. When I run PHPUnit Test on a specific package test class, the command always runs the same phpunit command which points to the first package folder, not the folder of the package that the test class is in, and therefore fails. The above works when running TestSuite, but not for individual methods or classes. Is there config that I can use to solve this problem?

**Comment by elonmallin** [comment]
This extension doesn't support multi-root workspaces unfortunately. It will just go with the first phpunit it finds or use the one set in config.
