### ISSUE TITLE
Error on run tests in directory with spaces in name

### ISSUE THREAD

**Issue by AeonDigital** [elonmallin/vscode-phpunit#34]
Hi, i think that the title is self explained about the problem that i´m was talking.
The error occour when use "F1" and select "PHPUnit Test" in a directory with spaces on the name.

Well... i´m opened the plugin source code and spend an hour in debug and i guess that i´ve found how to resolve this issue:

I think that this will resolve this case.
:)

In **phpunittest.ts** file, inside function **resolveContextArgs**, before **return args;**

```js
 public async resolveContextArgs(type: RunType, config): Promise<string[]> {

...


  if (args.length > 0) {            // new 
    args[0] = "'" + args[0] + "'";  // new
  }                                 // new

  return args;
}
```

**Comment by elonmallin** [comment]
Hi, I released an update today which should fix your issue. There might still be some problems if the path to your project has spaces in the name. Then please set absolute paths for all config vars you use and use the [windows short path](https://stackoverflow.com/questions/4051088/get-dos-path-instead-of-windows-path).
