### ISSUE TITLE
Run test nearest including the immediate class.

### ISSUE THREAD

**Issue by yaameen** [elonmallin/vscode-phpunit#39]
# Kudos to this really helpful extension.

Quite often while testing and TDD in general we use test the nearest `cmd+shift+p` and you get the options **PHPUnit** _Test Nearest_. 

Thanks to the feature this extension provides. It saves a ton of time.

However it fails to test when it comes to the class level. Also note that the methods are only recognised only when the method scope is `public`. 

The failure to pick the immediate class is resolved in the PR #38

**Comment by elonmallin** [comment]
Thanks a lot, it's merged =)
