### ISSUE TITLE
After update to vscode 1.5.1 the path of file tested is wrong

### ISSUE THREAD

**Issue by batopa** [elonmallin/vscode-phpunit#4]
On Linux trying to laucnh phpunit on specific file fails because of `phpunit` is launched with wrong path.

For example trying to test `./plugins/tests/test.php` inside `myproject` folder

```bash
vendor/bin/phpunit .plugins/tests/test.php
Cannot open file ".plugins/tests/test.php".
```

It miss `/` after `.` i.e. `./plugins/tests/test.php`.

It worked well until 1.5 release.

**Comment by elonmallin** [comment]
Yea I see the problem on Windows too, will have a look.

**Comment by elonmallin** [comment]
I fixed the path issue and published it to the marketplace. It works on windows and should work on linux too. Let me know if you have any problems.

It should also work on the older VSCode versions where the `/` was included in the relative path given by the VSCode api.

**Comment by batopa** [comment]
Yeah! Now it works again, thank you :+1:
