### ISSUE TITLE
Option "--color=always" is added recursivelly at console output at each "rerun last test'

### ISSUE THREAD

**Issue by Arkanius** [elonmallin/vscode-phpunit#45]
After the v4.1.0 the **--colors=always** option started to be default. At my config I used to use the **phpunit.colors** config setted as **--colors=always** without problems. Now, every time that I rerun some phpunit test one more "--color-always" is added to the console output.

## Repro
1. Set the config **phpunit.colors** with the value **--colors=always**
2. Run any test
3. Use the command to rerun last test

## Outcome
4. Check that every time you rerun any test one more "--colors=always" is added to your console output

## Expected outcome
The console shouldn't modify its output, like it was at previous versions. You can fix it by removing the *--color-always* setted in your *phpunit.colors* config (I just did it and works well)

## Logs / output / settings

![console-output](https://user-images.githubusercontent.com/6404401/81577458-d3b1dc80-937f-11ea-9a0f-bda004087842.jpeg)

settings.json
```json
"phpunit.command": "docker-compose exec php",
"phpunit.phpunit": "vendor/bin/phpunit",
"phpunit.paths": {
  "${workspaceFolder}": "/var/www/app"
}
```

Just an observation: I use the extension with docker

| **Environment** | **Values** |
| --- | --- |
| *Extension version* | v4.1.0 |
| *Operating system* | Ubuntu 18.04 |

**Comment by Arkanius** [comment]
Just to mention: I solved by removing the "--colors=always" that I used in the **phpunit.colors** config

**Comment by elonmallin** [comment]
Hi, thanks for the good bug report. Yea this is definitely not intended and was indeed added in the last patch as you said. Nice that you found the quick workaround!

I'll try and fix that.

**Comment by 9brada6** [comment]
I have the same problem, I just barely installed the extension, so I don't have much experience with it:
![image](https://user-images.githubusercontent.com/19844284/84476305-9b5f3000-ac96-11ea-94dc-fd86afedebe4.png)

And my settings:
![image](https://user-images.githubusercontent.com/19844284/84476360-add96980-ac96-11ea-8ca3-170525c48d01.png)

I didn't modify any --colors setting, just to make it work in a container.
