### ISSUE TITLE
Nothing is printed on the output console

### ISSUE THREAD

**Issue by viktorivanov** [elonmallin/vscode-phpunit#5]
Hi,
I'm running on Windows 10 and configured the extension as suggested, e.g. ```execPath``` is pointing where it should be... 
But when I run ```phpunit``` command no tests are run.

You can see from the screenshot below that the exact command works on the build-in command line.

![phpunit](https://cloud.githubusercontent.com/assets/6695695/21691471/53c5474e-d381-11e6-9754-9674db09436f.png)

Anyone else with Win10 having this issue?

**Comment by elonmallin** [comment]
Hey,

I think it might be that you need to use the `phpunit.bat`. I've used xampp too and I had the `execPath` pointing to `C:/xampp/php/phpunit.bat` or `C:\\xampp\\php\\phpunit.bat`. And I'm on Win10 too.

**Comment by viktorivanov** [comment]
That was it. 
Thank you @elonmallin.
