### ISSUE TITLE
PHPUnit cannot launch phpunit on Windows

### ISSUE THREAD

**Issue by OlafEichstaedt** [elonmallin/vscode-phpunit#50]
## Repro

1. install PHPUnit extension for VScode
2. create new directory
3. `composer require phpunit/phpunit`
4. set up phpunit.xml in project directory, see below
5. create some sample test
6. run `"vendor/bin/phpunit"` in the build in terminal
7. enjoy phpunit's result displayed in the terminal
8. CTRL+SHIFT+P and `PHPUnit Test`

## Outcome
```
> Executing task: php 'c:/PATH_TO_PROJECT_DIRECTORY/vendor/phpunit/phpunit/phpunit' --colors=always 'c:/PATH_TO_PROJECT_DIRECTORY/tests/unit/SampleTest.php' --filter public <

Could not open input file: 'c:/Users/olaf/workspace/phpunit_example/vendor/phpunit/phpunit/phpunit'
The terminal process "C:\WINDOWS\System32\cmd.exe /d /c php 'c:/Users/olaf/workspace/phpunit_example/vendor/phpunit/phpunit/phpunit' --colors=always 'c:/Users/olaf/workspace/phpunit_example/tests/unit/SampleTest.php' --filter public" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```
## Expected outcome
Unit tests should be run as when invoked from terminal's command line.

## Suspected error
The single quotes around the executable and the file name seem to be interpreted as part of the filename.  

When I run `php "c:/PATH_TO_PROJECT_DIRECTORY/vendor/phpunit/phpunit/phpunit" --colors=always "c:/PATH_TO_PROJECT_DIRECTORY/tests/unit/SampleTest.php" --filter public ` - i.e. with double quotes to delimit the file names- phpunit is invoked as expected.

### Environment
- Windows 10
- PHPUnit 9.4.0 by Sebastian Bergmann and contributors.
- Runtime:  PHP 7.4.3

### phpunit.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
    bootstrap="vendor/autoload.php"
    colors="true"
    verbose="true"
    stopOnFailure="true">
    <testsuites>
        <testsuite name="Test suite">
            <directory>tests</directory>
        </testsuite>
    </testsuites>
</phpunit>
```

**Comment by elonmallin** [comment]
Thanks for reporting the issue. Not sure why this happens for you. Single quotes works in other scenarios. I wonder if Vscode will use Powershell instead of cmd if you set it as the default in Vscode? Could you try that or another shell if possible?

**Comment by OlafEichstaedt** [comment]
Thanks for your feedback. After coming back to my PC and VScode, I can no longer reproduce the issue.

Running CTRL+SHIFT+P and `PHPUnit Test` and the like now works fine, e.g.:

```
Executing task: c:/<PATH_TO_PROJECT>/vendor/bin/phpunit.bat c:/<PATH_TO_PROJECT>/phpunit_example/tests/unit/SampleTest.php <

PHPUnit 9.4.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.3
Configuration: C:\<PATH_TO_PROJECT>\phpunit_example\phpunit.xml

...                                                                 3 / 3 (100%)

Time: 00:00.018, Memory: 6.00 MB

OK (3 tests, 5 assertions)

Terminal will be reused by tasks, press any key to close it.
```
I notice that VSCode now invokes phpunit.bat and that there are no more single quotes ... but I have no clue why this changed.

**Comment by elonmallin** [comment]
Ok great that it works now, I'll close the issue then :)

Odds are that something changed in the environment so another driver was used. It's set up to look for php and phpunit in settings, workspace and globally and now it found the phpunit.bat for windows you mentioned and used the right driver.
