### ISSUE TITLE
Add ability to run all tests in a file

### ISSUE THREAD

**Issue by dariusj18** [elonmallin/vscode-phpunit#51]
A feature in the (seemingly dead) `vscode-phpunit-extended` project is the ability to run all tests in a single file.  This can be very useful.

**Comment by elonmallin** [comment]
Hi, you mean like if there are multiple classes in one file? Otherwise it should already be possible to run the whole class right.

**Comment by dariusj18** [comment]
Oh, is this covered under the "PHPUnit Test" command? I think I misunderstood.

**Comment by elonmallin** [comment]
Yep it should work if you have the cursor on the class when you execute it. If the cursor is on a function it executes just the function =) Here's a gif from the readme https://raw.githubusercontent.com/elonmallin/vscode-phpunit/master/images/vscode-phpunit-test-class.gif

**Comment by dariusj18** [comment]
Oh, in that case I do think there should be a separate command to run the "nearest class", so I could run the entire class while my cursor is anywhere in the file. Although as you said above, if one so happened to have multiple classes in the same file, I would also think a run all tests in current file would be useful too, but I don't know if that has additional hurdles.

**Comment by elonmallin** [comment]
There's another use of the `PHPUnit Test` command if you put the cursor not on a function name or class name and run you will get a "quick pick" list where the last test you ran is at the top, then the class. So it's a down arrow and enter away from running the class test from anywhere in the file.

Ofc the downside is you can't hotkey it and you can't test multiple classes in the same file at once. Testing multiple classes I don't think is very common and probably not such a good practice. Testing the class with a hotkey might be but I don't think you test the whole class multiple times over, usually iterating on a function and testing that until it works, then running the full class test more seldomly so not as important. That said I'm happy to look at a PR =)

**Comment by dariusj18** [comment]
Thank you, I will investigate further.

**Comment by clementmas** [comment]
> Oh, in that case I do think there should be a separate command to run the "nearest class", so I could run the entire class while my cursor is anywhere in the file

That's the command I've been looking for. That'd be really useful.

Meanwhile, I have to move my cursor out or select "Run" and then pick the `class` option.
