### ISSUE TITLE
TestRunner is scanning whole fileystsem. Not only Workspace on Windows

### ISSUE THREAD

**Issue by Chinyeins** [elonmallin/vscode-phpunit#53]
## Repro
1. Add Extension to project
2. Open Testrunner tab
3. Check Output/PHPUnit Language Server

## Outcome
The Testrunner extension scans the whole file System for tests not only my workspace. I´s super slow and not what I would expect. Also warning that ***duplicate ID*** files are available.

## Expected outcome
Should only scan in workspace for tests

## Logs / output / settings
glob error [Error: EACCES: permission denied, scandir 'c:\Users\Christopher\AppData\Local\Microsoft\WindowsApps\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\Spotify.exe'] {
  errno: -4092,
  code: 'EACCES',
  syscall: 'scandir',
  path: 'c:\\Users\\XXX\\AppData\\Local\\Microsoft\\WindowsApps\\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\\Spotify.exe'
}
…

This is what it looks like on my machine. I´ve used the standard configs (settings)
![error_phpunitTestRunner](https://user-images.githubusercontent.com/13314966/115456806-dff71880-a223-11eb-91ae-faf71305b653.PNG)

| **Environment** | **Values** |
|---|---|
| *Extension version* |2.0.76 also older versions like v2.0.7.0 |
| *Operating system* | Windows 10 Pro |

**Comment by elonmallin** [comment]
Hi, this is not the right repo I'm afraid. There's another extension that has the test explorer :)
