### ISSUE TITLE
When phpunit.args is used, it is doubled for every repeating of the last test

### ISSUE THREAD

**Issue by BladeMF** [elonmallin/vscode-phpunit#56]
## Repro
1. Add some argument in config, e.g.
```json
	"phpunit.args": [
		"--testdox"
	],
```
2. Run a test
The command is: `Executing task: /some/path/vendor/bin/phpunit' --testdox --colors=always '/some/path'`
3. Execute `Rerun last test`
The command now is: `Executing task: /some/path/vendor/bin/phpunit' --testdox --colors=always --testdox --colors=always '/some/path'`
4. Execute `Rerun last test` again. `--testdox --colors=always` are added again.

## Expected outcome
The arguments for color and testdox to not be appended every time.

| **Environment** | **Values** |
|---|---|
| *Extension version* | 4.1.1 |
| *Operating system* | Windows 10 |

I really enjoy using your extension! 
Would you mind if I PR'd this?

**Comment by elonmallin** [comment]
Hi, I've been doing some work on this extension lately and it should be fixed in the latest version. Thanks for the bug report!
