### ISSUE TITLE
Suggestion: Make an option to not to force the output window open on test run

### ISSUE THREAD

**Issue by BladeMF** [elonmallin/vscode-phpunit#57]
When terminal is not in the same place as the output window (e.g. on the right), it is really annoying to have the output window popping up from the bottom and the terminal from the right. I really don't care about the output window as it only shows the command.

It makes sense to have an option that disables that behaviour:
[`this.channel.show(true);`](https://github.com/elonmallin/vscode-phpunit/blob/d3ac139231494af5bcbfc16b8d1c616e922e899e/src/phpunittest.ts#L348)

**Comment by elonmallin** [comment]
Hi, I removed the show completely, as you say it's useless since you wanna just see the terminal output or problems. Released update now
