### ISSUE TITLE
'PHPUnit Rerun Last Test' keep adding extra '--colors=always' argument

### ISSUE THREAD

**Issue by manhthang2504** [elonmallin/vscode-phpunit#60]
Run command `PHPUnit Rerun Last Test`, each time I use this command, it add another extra `--colors=always` argument

## Outcome
`Executing task: php 'path/my_project/vendor/phpunit/phpunit/phpunit' --colors=always --colors=always --colors=always --colors=always 'path/my_project/tests/Unit/MyTest.php' --filter test_function
`
## Expected outcome
`Executing task: php 'path/my_project/vendor/phpunit/phpunit/phpunit' --colors=always  'path/my_project/tests/Unit/MyTest.php' --filter test_function
`
(single --colors=always  only)

## Logs / output / settings
`Executing task: php 'path/my_project/vendor/phpunit/phpunit/phpunit' --colors=always --colors=always --colors=always --colors=always 'path/my_project/tests/Unit/MyTest.php' --filter test_function
`
| **Environment** | **Values** |
|---|---|
| *Extension version* | 4.1.1 |
| *Operating system* | Windows 11 |

**Comment by elonmallin** [comment]
Hi, thanks for the bug report. This should be fixed in the latest version.
