### ISSUE TITLE
Tests no longer running?

### ISSUE THREAD

**Issue by gijsbeijer** [elonmallin/vscode-phpunit#64]
Hi,

All of a sudden it looks like tests are no longer running. Is there anything I can do to debug what is happening.

Am I the only one facing problems?
Hope you can help, love the zero config on your extension!

EDIT: I checked the Output window for the extension and it shows nothing, Also checked the Log(Extension Host) filter but also nothing for this extension.

Regards Gijs

**Comment by elonmallin** [comment]
Hmm there should be output when it's running correctly and show the command also.

Did you solve it already?

**Comment by gijsbeijer** [comment]
Hi,

I forgot about my question here, so apologies for not replying here earlier.

Yes I managed to fix it. It just suddenly stopped working one day so I never thought it could be just a setting. But it was. I had to hardcode the path to the phpunit folder and that made it work again.

Sorry to have bothered you with this.
Regards Gijs
