### ISSUE TITLE
"Run build task" not works after installing the plugin.

### ISSUE THREAD

**Issue by quyle92** [elonmallin/vscode-phpunit#67]
Hi,
Thanks for creating great plugin. I have a question.
After I installed the plugin, I cannot perform the "run build task" command in my vscode anymore, it's just fetching constantly as shown in picture:
![image](https://user-images.githubusercontent.com/59790219/236385066-72f98d30-4081-4b5c-9127-f8eb0948aa96.png)
Can you please check?

Here is my vscode info:
Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:19:37.325Z (3 wks ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes

Thanks,
Q.

**Comment by elonmallin** [comment]
Hi, the extension has a new version, could you check again?

Can you share more what "Fetching build tasks..." do. This isn't happening for me so I assume you have some custom tasks in your workspace? What happens if you remove your tasks one by one, which task breaks it?

**Comment by elonmallin** [comment]
Closing this as it's quite old
